name: bbco
favicon: null
layout_spectrum: 0.6325767282396555
typography_spectrum: 0.15301952953450382
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.22197303897701204
  lightness: 0.09325002366676927
  saturation: 0.9544567081611603
  rhythmicContrast: 0.7367885739076883
purpose: []
