name: bbco
favicon: null
layout_spectrum: 0.5296
typography_spectrum: 0.15301952953450382
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#232325'
    - '#eeeeee'
    - '#a6a5a4'
    - '#777777'
    - '#c9c6c6'
  brandStrength: 0.5
  lightness: 0
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
